name: Test (parallel)

on: [workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:20

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'edge']

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run test
        env:
          BROWSER: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.browser }}
          path: screenshots/
